### ISSUE TITLE
PocObject IEquatable<T> implementation breaks nullness rules in VS 16.6.0 Preview 2.0

### ISSUE THREAD

**Issue by edfreeman** [corvus-dotnet/Corvus.Extensions.Newtonsoft.Json#79]
Microsoft is tightening the nullability rules, causing an additional warning. IEquatable<T>.Equals() looks like this:
```csharp
bool Equals([AllowNull] T other);
``` 
This new version of VS complains if you implement this method without specifying the nullable form of T. E.g.
 ```csharp
public bool Equals(PocObject other)
``` 
used to be allowed, but under the new rules it has to be:
 ```csharp
public bool Equals(PocObject? other)
```

**Comment by idg10** [comment]
Closed by #80
