### ISSUE TITLE
Remove requirement for classes which use PropertyBag to supply serialization settings

### ISSUE THREAD

**Issue by jongeorge1** [corvus-dotnet/Corvus.Extensions.Newtonsoft.Json#82]
At present, all classes which make use of `PropertyBag` need to provide a `JsonSerializerSettings` in order to create an instance which behaves as expected (if one isn't provided, `default(JsonSerializerSettings)` is used)

This means that classes which use PropertyBag tend to be created from the DI container which makes them hard to make them nullability aware, as it isn't possible to then set non-nullable properties via the constructor.

One solution to this would be to create a PropertyBag abstraction that doesn't have the `JsonSerializerSettings` dependency. We would then need to allow an implementation of the new abstraction via constructor parameters, with classes providing a default if one isn't supplied. The default would be a simple `IDictionary<string, object>`.

When deserializing, we would use a custom `JsonConverter` (as we already do for `PropertyBag`) to deserialize to a serialization-settings aware implementation that can then be injected into the type that's using it via the constructor initialisation mentioned above.

**Comment by mwadams** [comment]
There is a significant risk to this, which is that it encourages `PropertyBag` creation with serialization settings that *do not match* those of the rest of the world, and the whole thing breaks horribly.

**Comment by jongeorge1** [comment]
I genuinely have no recollection of the use case for this, or any reason why I opened it in the first place. So I'm going to close it.
