### ISSUE TITLE
PropertyBag's ownership of serialization settings is problematic

### ISSUE THREAD

**Issue by idg10** [corvus-dotnet/Corvus.Extensions.Newtonsoft.Json#86]
The  [`PropertyBag` class](https://github.com/corvus-dotnet/Corvus.Extensions.Newtonsoft.Json/blob/5d9dbeb94e9ff0deaccfeac069a4f0ecbb447b70/Solutions/Corvus.Extensions.Newtonsoft.Json/Corvus/Extensions/Json/PropertyBag.cs) in its current form has this property:

```csharp
public JsonSerializerSettings SerializerSettings { get; }
```

The implication of this is that the `PropertyBag` is responsible for deciding how to serialize things.

While there may well be scenarios in which that is desirable, it makes it problematic as an abstraction. The most obvious manifestation of the problem is that we now seem to have two `PropertyBag` types. There's a new one with no Json.NET dependencies: https://github.com/corvus-dotnet/Corvus.Extensions.System.Text.Json/blob/master/Solutions/Corvus.Extensions.System.Text.Json/Corvus/Extensions/Json/PropertyBag.cs

Anything that exposes a property of type `PropertyBag` now ties you to a specific implementation mechanism (either Json.NET or `System.Text.Json`). 

For example, we have this problem in [`Corvus.Tenancy`](https://github.com/corvus-dotnet/Corvus.Tenancy/). The [current version of the `ITenant`](https://github.com/corvus-dotnet/Corvus.Tenancy/blob/cb7590e2a9936b1a86c2d3510b8dc13a2ed43705/Solutions/Corvus.Tenancy.Abstractions/Corvus/Tenancy/ITenant.cs) abstraction defines this property:

```csharp
PropertyBag Properties { get; }
```

Firstly, that's the Json.NET `PropertyBag`, meaning that `ITenant` is basically incompatible with `System.Text.Json`. The `PropertyBag` in `Corvus.Extensions.System.Text.Json` has a logically equivalent but different property:

```csharp
public JsonSerializerOptions SerializerOptions { get; }
```

But even before we had two options for JSON serialization, this was less than ideal. Since `PropertyBag` implies "I'll manage my own serialization settings" this means that the `ITenant` abstraction now also implies that any implementation of `ITenant` also wants to manage its own serialization settings. But serialization settings are an implementation concern—consumers of `ITenant` have no need to be exposed to that. The logical model for an `ITenant`'s properties is a simple key/value store. And now that we have two different serialization options (Json.NET and `System.Text.Json`), the problem is more visible: by picking a particular `PropertyBag`, `ITenant` forces you into a particualr serialization technology.

In any case, it's weird that code that receives a tenant can access `tenant.Properties.SerializerOptions`.

(Having a particular implementation of `ITenant` be wired up to serialization infrastructure does make it possible for the `ITenant.Properties` to validate that values being set on the tenant are serializable. But `PropertyBag` exposes too much.)

One of the upshots of the unavoidable dependency `PropertyBag` forces on you is slightly strange code such as [this](https://github.com/corvus-dotnet/Corvus.Tenancy/blob/cb7590e2a9936b1a86c2d3510b8dc13a2ed43705/Solutions/Corvus.Tenancy.Storage.Azure.Blob/Corvus/Tenancy/Storage/Azure/TenantProviderBlobStore.cs#L166) in the `ITenantProvider` implementation over blob storage:

```csharp
Tenant child = this.serviceProvider.GetRequiredService<Tenant>();
```

and this somewhat weird code from the Marain `TenantMapper`:

```csharp
Client.Models.Tenant tenant = ((JObject)source).ToObject<Client.Models.Tenant>();
Tenant result = this.serviceProvider.GetRequiredService<Tenant>();
result.Properties = new PropertyBag(JObject.FromObject(tenant.Properties), result.Properties.SerializerSettings);
```

For consumers of abstractions that use property bags (e.g., users of `ITenant`), the only relevant methods are `TryGetValue` and `Set`. (And the `System.Text.Json` implementation currently doesn't support `Set`.)

We should consider whether it would be more appropriate just to expose an `IDictionary<string, object>`, as that's the idiomatic way to present the abstraction. Or, if supporting `System.Text.Json` means that `Set` ultimately looks like a bad idea, we could consider `IReadOnlyDictionary<string, object>` (and modifications to APIs that currently depend on `Set`; e.g., tenancy could move to a model where `ITenantProvider` offers methods to modify the properties, instead of having to modify the `tenant.Properties` and then pass the modified tenant to `UpdateTenantAsync`).

Alternatively, if we really need a bespoke abstraction to represent the "property bag" concept as it is understood by `Corvus.Extensions.Newtonsoft.Json` and `Corvus.Extensions.System.Text.Json` then we should decide where that abstraction lives (neither of those, since it would be a common abstraction) and what it should look like.

**Comment by mwadams** [comment]
**For context**

PropertyBag's promise and purpose is to keep things serialized until the last possible minute. When it was implemented there was no conception that there would be a mechanism other than Json.NET for managing that serialization.

The reason we have two implementations is that that assumption didn't hold true, and we did a quick spike of the Json.NET extensions to see if they could be replicated for `System.Text.Json`.

I agree that the weird code is weird, and clearly exists because the writer (almost certainly me!) didn't want to go through the pain of updating `Corvus.Extensions.Newtonsoft.Json` to write that piece of code.

I would prefer that generic `IPropertyBag`-type abstraction because we use it in other places too (e.g. CMS) and I would like a consistent abstraction of a just-in-time property bag deserializer.

I agree with all other points!

**Comment by idg10** [comment]
Should this new `IPropertyBag` support `Set<T>`? The Json.NET `PropertyBag` has it but the `System.Text.Json` one does not, and not without reason.

Given that the intent behind `PropertyBag` is inherently asymmetric (keep things in the serialized form until the last minute) I'm inclined to say that `Set<T>` does not belong. This would have implications for things like `ITenantProvider`—we'd need to offer a different mechanism for changing the properties of a tenant. (Today you do it by calling `tenant.Properties.Set(...)`. But I'm not sure we should.)

**Comment by mwadams** [comment]
I agree.

**Comment by idg10** [comment]
For the purposes of the present experiment I'm going to define `IPropertyBag` in this project. Obviously it doesn't belong here, because the whole point is to remove any tech-specific dependency. But since we don't yet have any `Corvus.Extensions.NoParticularJsonStack.Json` library to put it in, I'm prototyping in here for now.

But if we like where this ends up, it should definitely move...somewhere. Possibly yet another new library.

**Comment by mwadams** [comment]
I think `Corvus.Extensions.Json.Abstractions` would be not unreasonable place to put Json things that are not tied to any particular Json mechanism. And a quick trawl through our JSON-related code might find other things to put in there too.

**Comment by mwadams** [comment]
And we should probably rename this to Corvus.Extensions.Json and move everything JSON-related into it.

**Comment by mwadams** [comment]
(And retire the separate projects. It will allow us to evolve the different implementations together and avoid CI dependency hell)
